CREATE TABLE Admin (
    Id STRING(36) NOT NULL,
    UserId STRING(36) NOT NULL,
    RSOId STRING(36) NOT NULL,
    FOREIGN KEY(UserId) REFERENCES Users(Id),
    FOREIGN KEY(RSOId) REFERENCES RSO(Id)
) PRIMARY KEY(Id);
