CREATE TABLE Event (
    Id STRING(36) NOT NULL,
    LocationId STRING(36)  NOT NULL,
    RsoId STRING(36) NOT NULL,
    Name STRING(100) NOT NULL,
    Description STRING(MAX) NOT NULL,
    Category STRING(20) NOT NULL,
    StartTime TIMESTAMP NOT NULL,
    EndTime TIMESTAMP NOT NULL,
    FOREIGN KEY(LocationId) REFERENCES Location(Id),
    FOREIGN KEY(RsoId) REFERENCES RSO(Id)
) PRIMARY KEY(Id);

CREATE UNIQUE NULL_FILTERED INDEX TimeAndSpaceConstraint ON Event (StartTime, LocationId);
