CREATE TABLE Event (
    Id STRING(36) NOT NULL,
    AID STRING(36) NOT NULL,
    Name STRING(100) NOT NULL,
    Description STRING(MAX) NOT NULL,
    Category STRING(20) NOT NULL,
    Time DATETIME NOT NULL,
    LocationId NOT NULL,
    FOREIGN KEY(LocationId) REFERENCES Location(Id),
    FOREIGN KEY(AID) REFERENCES Admin(Id)
);
