CREATE TABLE Member (
    Id STRING(36) NOT NULL,
    UserId STRING(36) NOT NULL,
    RSOId STRING(36) NOT NULL,
    FOREIGN KEY(RSOId) REFERENCES RSO(Id),
    FOREIGN KEY(UserId) REFERENCES User(Id)
);
