CREATE TABLE Rating (
    Id STRING(36) NOT NULL,
    EventId STRING(36) NOT NULL,
    UserId STRING(36) NOT NULL,
    Value INT64 NOT NULL,
    FOREIGN KEY(EventId) REFERENCES Event(Id),
    FOREIGN KEY(UserId) REFERENCES User(Id)
) PRIMARY KEY(Id);
