CREATE TABLE RsoEvent (
    Id STRING(36) NOT NULL,
    EventId STRING(36) NOT NULL,
    RSOId STRING(36) NOT NULL,
    FOREIGN KEY(EventId) REFERENCES Event(Id),
    FOREIGN KEY(RSOId) REFERENCES RSO(Id)
) PRIMARY KEY(Id);
