INSERT INTO University (Id, Name, Address, Description, NumberOfStudents) VALUES ('6eafb5de-0890-b625-c204-c948540ce33d', "University of Central Florida", "4000 Central Florida Blvd, Orlando, FL 32816", "The University of Central Florida is a public research university with its main campus in unincorporated Orange County, Florida. UCF also has nine smaller regional campuses throughout central Florida. It is part of the State University System of Florida.", 61111);

INSERT INTO University (Id, Name, Address, Description, NumberOfStudents) VALUES ('b1c905da-d477-49fe-af2f-1caf1e7544ce', "University of Florida", "201 Criser Hall PO Box 114000 Gainesville, FL 32611", "The University of Florida is a public land-grant research university in Gainesville, Florida. It is a senior member of the State University System of Florida, traces its origins to 1853, and has operated continuously on its Gainesville campus since September 1906.",  34881);

INSERT INTO University (Id, Name, Address, Description, NumberOfStudents) VALUES ('8cf421e8-4350-405e-8055-f0b7384c92e6',  "Valencia College", "SSB - Student Services Building, 1800 S Kirkman Rd, Orlando, FL 32811", "Valencia College is a public college in Orlando, Florida. It is part of the Florida College System. The college was founded in 1967 as Valencia Junior College and changed its name in 2010 because the academic scope of the school had expanded to include bachelor's degrees.", 36915);

INSERT INTO University (Id, Name, Address, Description, NumberOfStudents) VALUES ('951b42c7-2b3f-4e58-92e1-90574d5a1b0d', "Harvard University", "Cambridge, MA 02138", "Harvard University is a private Ivy League research university in Cambridge, Massachusetts. Established in 1636 and named for its first benefactor clergyman John Harvard, Harvard is the oldest institution of higher learning in the United States and among the most prestigious in the world.", 31023);

INSERT INTO University (Id, Name, Address, Description, NumberOfStudents) VALUES ('0a1f90d4-bd46-4c4f-b41f-4c6d4fc02dd9', "Massachusetts Institute of Technology", "77 Massachusetts Ave, Cambridge, MA 02139", "The Massachusetts Institute of Technology is a private land-grant research university in Cambridge, Massachusetts. The institute has an urban campus that extends more than a mile alongside the Charles River. The Institute is a member of the Association of American Universities.", 11177);

INSERT INTO University (Id, Name, Address, Description, NumberOfStudents) VALUES ('22df0a9c-c173-4682-a2a1-206a56e2588f', "Stanford University", "450 Serra Mall, Stanford, CA 94305", "Stanford University is a private research university in Stanford, California. Stanford is known for its academic strength, wealth, selectivity, proximity to Silicon Valley, and ranking as one of the world's top universities.", 17135);

INSERT INTO University (Id, Name, Address, Description, NumberOfStudents) VALUES ('96cc81e6-8a9e-4a02-93c2-21eeb5d09843', "California Institute of Technology", "1200 E California Blvd, Pasadena, CA 91125", "The California Institute of Technology is a private research university in Pasadena, California. Caltech has six academic divisions with strong emphasis on science and engineering, managing JPL for NASA, and operating its own jet propulsion laboratory.", 2333);

INSERT INTO University (Id, Name, Address, Description, NumberOfStudents) VALUES ('d7566c1e-fb68-4691-bd60-91327ebc23da', "Princeton University", "Princeton, NJ 08544", "Princeton University is a private Ivy League research university in Princeton, New Jersey. Founded in 1746 in Elizabeth as the College of New Jersey, Princeton is the fourth-oldest institution of higher education in the United States and one of the nine colonial colleges chartered before the American Revolution.", 8462);

INSERT INTO University (Id, Name, Address, Description, NumberOfStudents) VALUES ('a93a0fa8-ec25-4b3c-93e3-e04c1299b5cf', "Columbia University", "116th St & Broadway, New York, NY 10027", "Columbia University is a private Ivy League research university in New York City. Established in 1754 as King's College, Columbia has been a leader in higher education in the nation and around the world for more than 250 years.", 33838);

INSERT INTO University (Id, Name, Address, Description, NumberOfStudents) VALUES ('b3ec01e3-3d98-4416-a94e-2b0896aaf7c5', "Yale University", "New Haven, CT 06520", "Yale University is a private Ivy League research university in New Haven, Connecticut. Founded in 1701, it is the third-oldest institution of higher education in the United States and one of the nine Colonial Colleges chartered before the American Revolution.", 13810);
